---
  - name: Stopping rsyslog service
    service:
      name: "rsyslog"
      state: stopped
    when: ansible_os_family == "Debian"

  - name: Clearing audit logs
    file:
      path: "{{ item }}"
      state: absent
    with_items: audit_logs

  - name: Cleaning up tmp directories
    command: "rm -rf {{ item }}"
    with_items:
      - '/tmp/*'
      - '/var/tmp/*'

  - name: Adding ssh key re-generation command to rc.local
    command: "sed -i '$ i dpkg-reconfigure openssh-server' /etc/rc.local"

  - name: Making sure rc.local only runs once
    command: "sed -i '$ i mv /etc/rc.local.orig /etc/rc.local' /etc/rc.local"

  - name: Getting SSH host keys
    shell: ls /etc/ssh/ssh_host_*
    register: ssh_host_files

  - name: Deleting SSH host keys
    file:
      path: "{{ item }}"
      state: absent
    with_items: "{{ssh_host_files.stdout_lines}}"
...
